<?php

declare(strict_types=1);

namespace Framework\Routing;

use RuntimeException;

/**
 * Production-ben a route-tábla előre kiszámítva egy PHP-fájlból töltődik,
 * elkerülve a reflection-scan költségét minden requesten. A cache:
 *
 *   - PHP-fájl, ami egyetlen array literal-t ad vissza (opcache-friendly).
 *   - Atomic write: temp fájl + rename.
 *   - Verzióelt — ha a séma változik (pl. új mezők a route-paramekben), a
 *     `VERSION` konstans inkrementálódik és a régi cache automatikusan invalidálódik.
 */
final class RouteCache
{
    public const VERSION = 1;

    public function __construct(private readonly string $cacheFile)
    {
    }

    /**
     * @return array<string, array<string, mixed>>|null
     */
    public function load(): ?array
    {
        if (!is_file($this->cacheFile)) {
            return null;
        }

        /** @var mixed $data */
        $data = @include $this->cacheFile;
        if (!is_array($data) || ($data['version'] ?? null) !== self::VERSION) {
            return null;
        }
        $routes = $data['routes'] ?? null;
        if (!is_array($routes)) {
            return null;
        }
        /** @var array<string, array<string, mixed>> $routes */
        return $routes;
    }

    /**
     * @param array<string, array<string, mixed>> $routes
     */
    public function save(array $routes): void
    {
        $dir = dirname($this->cacheFile);
        if (!is_dir($dir) && !mkdir($dir, 0o755, true) && !is_dir($dir)) {
            throw new RuntimeException("Failed to create cache directory: {$dir}");
        }

        $payload = [
            'version' => self::VERSION,
            'generated_at' => date('c'),
            'routes' => $routes,
        ];
        $php = "<?php\n\n// Auto-generated by bin/console route:cache. Do not edit.\nreturn " . var_export($payload, true) . ";\n";

        $tmp = $this->cacheFile . '.' . bin2hex(random_bytes(4)) . '.tmp';
        if (file_put_contents($tmp, $php, LOCK_EX) === false) {
            throw new RuntimeException("Failed to write cache tempfile: {$tmp}");
        }
        if (!rename($tmp, $this->cacheFile)) {
            @unlink($tmp);
            throw new RuntimeException("Failed to atomically install cache file: {$this->cacheFile}");
        }
    }

    public function clear(): void
    {
        if (is_file($this->cacheFile)) {
            unlink($this->cacheFile);
        }
    }

    public function path(): string
    {
        return $this->cacheFile;
    }
}
