services:
  app:
    container_name: application-cont
    platform: linux/amd64
    build:
      context: ./docker/apache
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - antarctic-web
    volumes:
      - ./src:/var/www
  database:
    container_name: application-db-cont
    platform: linux/amd64
    build:
      context: ./docker/${DATABASE}
      dockerfile: Dockerfile
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    environment:
      - POSTGRES_USER=${DATABASE_USER} # The PostgreSQL user (useful to connect to the database)
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_INITDB_ARGS=--auth-host=md5 --locale=hu_HU.UTF-8
    networks:
      - antarctic-web
    volumes:
      - ~/.local/share/antarctic/data/:/var/lib/postgresql/data/

networks:
  antarctic-web:
    name: "antarctic-web"
    driver: bridge